### ISSUE TITLE
RSSI value not always visible

### ISSUE THREAD

**Issue by Cosmicbase** [Barma-lej/landroid-card#138]
Describe the issue:
Wlan value is missing as soon as the robot drive or stand in the docking Station. 

Look my pictures.

What version of Home Assistant Core has the issue?
Home Assistant 2023.4.5

What was the last working version of Home Assistant Core?
No response

What version of the Landroid Cloud integration do you have installed
v3.0.0b4

What type of installation are you running?
Home Assistant OS
Home Assistant 2023.4.5

Which make and model is the mower used for this integration?
WR141E

Relevant log entries
None
Additional information
v3.0.0b4

![Screenshot_20230418_165933_Chrome](https://user-images.githubusercontent.com/31271212/232832472-1b65685a-5ecf-453c-aa66-ea2c024d3ee6.jpg)
![Screenshot_20230418_170242_Chrome](https://user-images.githubusercontent.com/31271212/232832484-deea8e7a-7616-45a4-b338-1da166b4295d.jpg)

**Comment by Barma-lej** [comment]
removed personal information

**Comment by Barma-lej** [comment]
Check RSSI attribute during the mowing.

**Comment by Cosmicbase** [comment]
Yes, under mowing, the RSSI is active.  But it could also be that it is a pure synchronization problem on the part of Positec.  They're having problems at the moment.
I'll keep watching.

**Comment by Cosmicbase** [comment]
The RSSI status is not active when idle. The battery status, on the other hand, is visible.

**Comment by Barma-lej** [comment]
I don't see any problems with the card.
Wait for 3.29 Update. There is a WiFi Firmware update
[Betaversion 3.29b17 (DE)](https://www.roboter-forum.com/threads/betaversion-3-29b17.60767/)

**Comment by Cosmicbase** [comment]
> I don't see any problems with the card. Wait for 3.29 Update. There is a WiFi Firmware update [Betaversion 3.29b17 (DE)](https://www.roboter-forum.com/threads/betaversion-3-29b17.60767/)

I already installed the firmware last year. But there may still be problems beyond that.

**Comment by Barma-lej** [comment]
Sorry, i can't here help you. I think the problem either with hardware or WiFi connection
