### ISSUE TITLE
Is not a error but also not ok

### ISSUE THREAD

**Issue by virusczz** [Barma-lej/landroid-card#139]
i have the leatest beta version of cloud plugin, and also latest car.
what i finded is that in the left upper corner is the WIFI signal. I am not ussing the wifi signal i am ussing the RadioLink. Why the card is not showing the actual signal for radio link ? 
(you know when RadioLink => no Wifi ussed) . Or is possible to change this somehow ? 

i can share picture of the App (ios) and the card. In the app i have 100% signal in the card 2% (that's why i ordered and instaled the Radiolink :) )

Thank you

**Comment by Barma-lej** [comment]
The card get info from the integration. There's no information about the radiolink in the entity attributes
