### ISSUE TITLE
Card doesn't load using chrome

### ISSUE THREAD

**Issue by cm86** [Barma-lej/landroid-card#14]
Hello the card doesn't load in Chrome...
i have already deleted website data and cookies / cache.
If i'm using the private tab it also doesn't load.

Here is the output of the webkonsole...

`landroid-card.js:1 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Number.toLocaleString (<anonymous>)
    at n.value (landroid-card.js:1:372557)
    at landroid-card.js:1:377957
    at Array.map (<anonymous>)
    at n.value (landroid-card.js:1:377512)
    at landroid-card.js:1:377557
    at Array.map (<anonymous>)
    at n.value (landroid-card.js:1:377512)
    at n.value (landroid-card.js:1:377234)
    at n.value (landroid-card.js:1:385246)
value @ landroid-card.js:1
(anonym) @ landroid-card.js:1
value @ landroid-card.js:1
(anonym) @ landroid-card.js:1
value @ landroid-card.js:1
value @ landroid-card.js:1
value @ landroid-card.js:1
update @ landroid-card.js:1
performUpdate @ landroid-card.js:1
scheduleUpdate @ landroid-card.js:1
_$Ej @ landroid-card.js:1
await in _$Ej (async)
requestUpdate @ landroid-card.js:1
set @ landroid-card.js:1
value @ hui-light-card.ts:35
_$AE @ styles.ts:369
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
set @ styles.ts:369
(anonym) @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
set @ styles.ts:369
value @ hui-root.ts:551
_$AE @ styles.ts:369
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
set @ styles.ts:369
k @ styles.ts:369
_$AI @ styles.ts:369
m @ styles.ts:369
T @ styles.ts:369
_$AI @ styles.ts:369
S @ styles.ts:369
update @ styles.ts:369
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
set @ styles.ts:369
value @ app-drawer-layout.js:189
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
set @ styles.ts:369
k @ styles.ts:369
_$AI @ styles.ts:369
m @ styles.ts:369
T @ styles.ts:369
_$AI @ styles.ts:369
S @ styles.ts:369
update @ styles.ts:369
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
set @ styles.ts:369
k @ styles.ts:369
_$AI @ styles.ts:369
m @ styles.ts:369
T @ styles.ts:369
_$AI @ styles.ts:369
S @ styles.ts:369
update @ styles.ts:369
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
set @ styles.ts:369
value @ styles.ts:369
(anonym) @ styles.ts:369
s @ core.2895f1d4.js:1
(anonym) @ core.2895f1d4.js:1
e.subscribeMessage.type @ core.2895f1d4.js:1
_handleMessage @ core.2895f1d4.js:1`

**Comment by Barma-lej** [comment]
What is your version of landroid-card?
See here #10

**Comment by cm86** [comment]
Hello @Barma-lej ,
i'm using version 0.2.1.

**Comment by Barma-lej** [comment]
Please publish attributes of your mower

**Comment by cm86** [comment]
```battery_level: 76
battery_icon: mdi:battery-80
accessories:
  ultrasonic: true
battery:
  cycles:
    total: 1717
    current: 0
    reset_at: null
    reset_time: null
  temperature: 21.7
  voltage: 18.56
  percent: 76
  charging: false
blades:
  total_on: 252963
  reset_at: 68136
  reset_time: '2020-08-23T18:41:40+02:00'
  current_on: 184827
error:
  id: 0
  description: no error
firmware:
  auto_upgrade: false
  version: 3.27
locked: false
mac_address: XXXXXXXX
model: Landroid M1000
online: true
orientation:
  pitch: -2.8
  roll: -2.4
  yaw: 289.9
party_mode_enabled: true
rain_sensor:
  delay: 0
  triggered: true
  remaining: 0
rssi: -70
schedule:
  next_schedule_start: '2022-07-26T18:00:00+02:00'
  time_extension: 0
  active: true
  auto_schedule:
    settings: {}
    enabled: null
  primary:
    monday:
      start: '07:00'
      end: '15:00'
      duration: 480
      boundary: false
    tuesday:
      start: '07:00'
      end: '15:00'
      duration: 480
      boundary: false
    wednesday:
      start: '07:00'
      end: '15:00'
      duration: 480
      boundary: true
    thursday:
      start: '07:00'
      end: '15:00'
      duration: 480
      boundary: false
    friday:
      start: '07:00'
      end: '15:00'
      duration: 480
      boundary: false
    saturday:
      start: '07:00'
      end: '15:00'
      duration: 480
      boundary: false
    sunday:
      start: '07:00'
      end: '15:00'
      duration: 480
      boundary: true
  secondary:
    monday:
      start: '18:00'
      end: '00:00'
      duration: 360
      boundary: false
    tuesday:
      start: '18:00'
      end: '00:00'
      duration: 360
      boundary: false
    wednesday:
      start: '18:00'
      end: '00:00'
      duration: 360
      boundary: false
    thursday:
      start: '18:00'
      end: '00:00'
      duration: 360
      boundary: false
    friday:
      start: '18:00'
      end: '00:00'
      duration: 360
      boundary: false
    saturday:
      start: '18:00'
      end: '00:00'
      duration: 360
      boundary: false
    sunday:
      start: '18:00'
      end: '00:00'
      duration: 360
      boundary: false
serial_number: XXXXXXXXXXXX
statistics:
  worktime_blades_on: 252963
  distance: 4226582
  worktime_total: 274532
status_info:
  id: 7
  description: mowing
time_zone: Europe/Berlin
torque: 0
state_updated_at: '2022-07-26T13:24:55+02:00'
zone:
  current: 1
  next: 0
  index: 3
  indicies:
    - 0
    - 1
    - 0
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  starting_point:
    - 3
    - 138
    - 0
    - 0
capabilities:
  - Edge Cut
  - One-Time-Schedule
  - Party Mode
  - Motor Torque
mqtt_connected: true
supported_landroid_features: 16383
daily_progress: 46
next_scheduled_start: '2022-07-26T18:00:00+02:00'
device_class: landroid_cloud__state
friendly_name: Manni
supported_features: 12500
```

**Comment by cm86** [comment]
i have already restarted hassio several times.
sometimes it's loading with just this error  message...
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "landroid-card-editor" has already been used with this registry
```

But that's really random...

**Comment by Barma-lej** [comment]
Go to _Configuration_ → _Lovelace Dashboards_ → _Resources Tab_ and check how many times do you have landroid-card there

**Comment by cm86** [comment]
I have it two times there…

because i have installed it manually before…

![6F9D108D-2597-49EA-B2F5-1030F691FE61](https://user-images.githubusercontent.com/14919688/180999071-c99ecd0d-39dd-4aaa-8a42-a7887def2414.png)

**Comment by Barma-lej** [comment]
Remove manual installation

**Comment by cm86** [comment]
I deleted the manually added one...
now it comes up correctly...

Thanks in advance

**Comment by Barma-lej** [comment]
Please close the issue

**Comment by cm86** [comment]
There is also no error message more in the webkonsole...
