### ISSUE TITLE
zone set doesent work

### ISSUE THREAD

**Issue by ilgio** [Barma-lej/landroid-card#149]
I have homeassistant updated.
and the zoneset doesent work, and view a error:

Invocazione del servizio landroid_cloud/setzone non
riuscita. Cannot request this zone as it is not defined.

**Comment by Barma-lej** [comment]
It was an integration's bug

**Comment by ilgio** [comment]
there have been updates to the landroid integration, but the zones still don't work

**Comment by Barma-lej** [comment]
log?

**Comment by ilgio** [comment]
ok, now work, but need a refresh
thx

**Comment by ilgio** [comment]
Now doesent work it. where do I view log of this card?

**Comment by Barma-lej** [comment]
**This isn't a card's bug**

You can self call the service `landroid_cloud.setzone` from [**Developer tools**](https://www.home-assistant.io/docs/tools/dev-tools/#services) and check if it works without card

> where do I view log of this card?

https://www.home-assistant.io/integrations/system_log/

Please RTFM

**Comment by ilgio** [comment]
there is some problem with the integration maybe.. watch the video and you will see that when I select the zones, only some times the current changes, while the index always changes
[video](https://youtu.be/T3YC2K1wbAk)

**Comment by Barma-lej** [comment]
And now the same but without card

**Comment by ilgio** [comment]
Now. I deleted the integration in HACS,
I rebooted, reinstalled and re-entered my login and password.. now it works
bohh
