### ISSUE TITLE
Hide next scheduled start part of status

### ISSUE THREAD

**Issue by bluediamond1984** [Barma-lej/landroid-card#150]
My status line is always showing `Docked - Next scheduled start 01/01/1970, 01:00`, because I don't use the schedule from Worx. I'm only interested in the first part of the status and `show_status` is showing the entire line, or nothing.

Could an option be added to hide the `next scheduled start` part of the status?

**Comment by Barma-lej** [comment]
I'll check if the current date and time is less than the `next scheduled start`, then the next start will be shown

**Comment by Barma-lej** [comment]
Fixed in https://github.com/Barma-lej/landroid-card/releases/tag/0.2.5
