### ISSUE TITLE
Dutch translations are not working

### ISSUE THREAD

**Issue by CasparTheBridge** [Barma-lej/landroid-card#151]
## **Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser. [See here](https://github.com/Barma-lej/landroid-card/issues/3#issuecomment-1176298240)

## **Describe the bug**

The dutch translations are not working. The 'nl.json' is existing and also the 'localize.js' is updated to use this file. Is there a general issue for the translations or something I need to adjust in the nl-translations file?

## **Steps to reproduce**

Language setting of user is in Dutch but the card is still the default (English)

## **Expected behavior**

The right translations in the card

## **Log, errors**

No specific errors in the 'Home Assistant Core' log files. Only the warning about using the custom integration.

## **Screenshots**

Screenshot of the card with english texts and with a pop-up with dutch content (standard HA entity screen) in the comment below

## **Versions:**

- Release: 0.2.3
- Browser: chrome & edge
- HomeAssistant version: 2023.5.3
- Landroid_cloud integration 3.0.1

**Comment by CasparTheBridge** [comment]
![Landroid card not translated](https://github.com/Barma-lej/landroid-card/assets/50670032/48567481-ff60-4a14-b8a6-08b9ae7151c0)

**Comment by Barma-lej** [comment]
Wait next release, it was an error in slovenian language

**Comment by Barma-lej** [comment]
Fixed in https://github.com/Barma-lej/landroid-card/releases/tag/0.2.5
