### ISSUE TITLE
Cannot upgrade past 0.2.2

### ISSUE THREAD

**Issue by spiralfive** [Barma-lej/landroid-card#163]
I was running the 0.2.2 version of the card without issue and tried to upgrade today to the 0.2.5 version. When I do so - I get an error that the element does not exist. This same issue happens with 0.2.3. 

![image](https://github.com/Barma-lej/landroid-card/assets/26095643/9e9e8ceb-779d-4080-b171-9312d589ad6b)

There is this error in the console when trying to view the dashboard with the custom cards on it:
![image](https://github.com/Barma-lej/landroid-card/assets/26095643/c10f23f3-fb0a-483e-bf1e-ebbce4400ad1)

I installed this totally through HACS - no manual config was done. If I roll back to 0.2.2, it works fine again. I tried clearing my cache and I wiped the frontend cache on the app. This changes nothing, the error remains. I tried to also manually run the javascript file in the console, just to see what would happen, and the same error occurs. 

I also already verified there are no duplicated resources, that was the cause with another issue I found when searching.
![image](https://github.com/Barma-lej/landroid-card/assets/26095643/ba422e75-03c9-4724-8937-33493a1ac93a)

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest

**Comment by Barma-lej** [comment]
There is a conflict with vacuum-card

**Comment by Barma-lej** [comment]
Please check the version 0.2.6

**Comment by spiralfive** [comment]
That fixed it - thanks!

**Comment by denysdovhan** [comment]
Please bump `ha-template` to `1.2.2`. The issue should be resolved there.

**Comment by simowdas** [comment]
Same with me. In version 0.2.7 it doesn't work either

**Comment by Barma-lej** [comment]
> Same with me. In version 0.2.7 it doesn't work either

Please log from the browser's console

**Comment by simowdas** [comment]
I've checked on browser. Seems ok. Looks like the problem is only on android app (ver. 2023.6.0-full)

**Comment by Barma-lej** [comment]
Clean app cache

**Comment by simowdas** [comment]
Looks good :). THX
