### ISSUE TITLE
Translation of the Error. 

### ISSUE THREAD

**Issue by Danit2** [Barma-lej/landroid-card#18]
**Is your feature request related to a problem? Please describe.**
The error is not translatet. See Picture:
![image](https://user-images.githubusercontent.com/71522810/182108588-d6b87993-2560-4287-97dd-af12fea85d76.png)

**Describe the solution you'd like**
Add the errors in the translation file.

**Comment by Barma-lej** [comment]
Thank you. I don't know all error descriptions, so i'll add them during developing with your help 😉

**Comment by Danit2** [comment]
Ok cool thanks. 
You can tell me where i can update the translation. So i can translate for you.

**Comment by Barma-lej** [comment]
Added in [0.2.3](https://github.com/Barma-lej/landroid-card/releases/tag/0.2.3)

**Comment by Danit2** [comment]
Thanks
