### ISSUE TITLE
Animation not working

### ISSUE THREAD

**Issue by TvoDebug** [Barma-lej/landroid-card#207]
## **Before submitting a bug**

[ x ] I updated to the latest version available
[ x ] I cleared the cache of my browser. [See here](https://github.com/Barma-lej/landroid-card/issues/3#issuecomment-1176298240)

## **Describe the bug**

Since 2023.9 the animation stopped working. The image is not moving anymore when mower is active.
Still persisting in 2023.10
As opposed to this, the vacuum cleaning card is showing the wanted behavior.

## **Steps to reproduce**

1. Open panel
2. Watch the image
3. Image not animated

## **Expected behavior**

Image animated

## **Versions:**

- Browser: chrome
- HomeAssistant version: 2023.10.0
- Landroid_cloud integration: latest

**Comment by Barma-lej** [comment]
Check the new release https://github.com/Barma-lej/landroid-card/releases/tag/0.3.2 and close the issue if it's works

**Comment by TvoDebug** [comment]
Perfect Thanks!, new release was the solution and fixed my issue!
