### ISSUE TITLE
Modify card to support lawn_mower type of entity

### ISSUE THREAD

**Issue by sshalyminov** [Barma-lej/landroid-card#218]
**Is your feature request related to a problem? Please describe.**

Landroid integration starting v4.0.0b1 moving to lawn_mower entity type:

> Changes
> 🛠 Breaking Changes
> #458 Migrating from vacuum to lawn_mower platform @MTrab
> Old vacuum entity will become unavailable and a new lawn_mower entity will be created - this is expected behaviour

https://github.com/MTrab/landroid_cloud/releases/tag/v4.0.0b1

**Describe the solution you'd like**

Modify card to support lawn_mower type of entity

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by Barma-lej** [comment]
Всё будет, не беспокойся 🙂

**Comment by Barma-lej** [comment]
There is a new beta [1.0.0b1](https://github.com/Barma-lej/landroid-card/releases/tag/1.0.0b1). Install it only you have Landroid Cloud version > 4.0.0

**Comment by sshalyminov** [comment]
Работает отлично!

**Comment by MTrab** [comment]
Do keep in mind that v4 will have MAJOR changes - not only the migration to the lawn_mower platform
So please keep following the beta releases over the next period

**Comment by MTrab** [comment]
Landroid_cloud integration v4.0.0b2 released with even more breaking changes

**Comment by Barma-lej** [comment]
There is a new beta version [1.0.0b2](https://github.com/Barma-lej/landroid-card/releases/tag/1.0.0b2) here
