### ISSUE TITLE
information not present in the landroid card

### ISSUE THREAD

**Issue by Cosmicbase** [Barma-lej/landroid-card#222]
https://github.com/Barma-lej/landroid-card/assets/31271212/406e6510-588a-4e3d-919a-18c346e51c0e

Describe the issue
All information is incorrect, see also picture.
For example: WLAN, Timestamp, PartyMode,

Edgecut, mowing and the battery informations are seems right.
I don't know if the errors are due to the card.
The cloud data seems to be correct.

What version of Home Assistant Core has the issue?
2023.11.2

What was the last working version of Home Assistant Core?
No response

What version of the Landroid Cloud integration do you have installed
v4.0.0b3

What type of installation are you running?
Home Assistant Supervised

Which make and model is the mower used for this integration?
WR141E

Diagnostics information (NOT log entries!)

![282935320-be823bb2-5311-448c-b77a-a903bf5b7089](https://github.com/Barma-lej/landroid-card/assets/31271212/7ffba02f-5fd2-4dab-b123-56156e4e1a27)

**Comment by Barma-lej** [comment]
Either version 0.3.2 nor version 1.0.0b1 of the Landroid Card doesn't support Landroid Cloud v4.0.0b3

**Comment by Cosmicbase** [comment]
What should I do now? Waiting for an update?

**Comment by Barma-lej** [comment]
Waiting on update or downgrading Landroid Cloud

**Comment by Cosmicbase** [comment]
> Waiting on update or downgrading Landroid Cloud

Which version of Landroid Cloud version works with 1.0.0b1.
I have to wait for an update from you?

**Comment by MTrab** [comment]
4.0.0b1

**Comment by Cosmicbase** [comment]
> 4.0.0b1
@MTrab Thx
This means that a Landroid Card update should be available for Landroid Cloud v4.0.0b3.

The problem is that I have already rewritten the new entities and have a lot of automations.
I just don't want to rewrite anymore. Maybe I can wait for an update if it doesn't take too long.

@Barma-lej 
Do you know when an update will come?

**Comment by MTrab** [comment]
Remember that you are on a bleeding edge when using the beta version - LOTS of changes are coming, not near done yet.
So the issues you see by using beta versions are expected - as we are 2 individuals developing landroid_cloud and landroid card, DO NOT expect them to be released at the same time, especially not when on the beta channel.

**Comment by Barma-lej** [comment]
Wenn ich Zeit habe, Markus. Und wenn ein Release von Landroid Cloud veröffentlicht wird.

**Comment by Cosmicbase** [comment]
@Barma-lej Dann warte ich auf das Update. 
@MTrab Thank you for your tireless efforts.

**Comment by Barma-lej** [comment]
There is a new beta version [1.0.0b2](https://github.com/Barma-lej/landroid-card/releases/tag/1.0.0b2) here
