### ISSUE TITLE
After update Landroid Cloud to version 4.0.0 mover is not visible in card

### ISSUE THREAD

**Issue by DeimicUser** [Barma-lej/landroid-card#237]
## **Before submitting a bug**

[ ] I updated to the latest version available
[ ] I cleared the cache of my browser. [See here](https://github.com/Barma-lej/landroid-card/issues/3#issuecomment-1176298240)

## **Steps to reproduce**

3. See error

## **Log, errors**

Error in the log of Home Assistant: **Settings -> System -> Logs**
[Error in browser debugger console](https://javascript.info/debugging-chrome#console)

## **Screenshots**

For example, JavaScript errors are shown [in the browser's web inspector](https://javascript.info/debugging-chrome#console) (if applicable).

## **Versions:**

- Release: [e.g. 0.2.0]
- Browser: [e.g. chrome, safari]
- HomeAssistant version: [e.g 2022.8.0]
- Landroid_cloud integration [e.g 2.3.0]

**Comment by Barma-lej** [comment]
#218
#222

**Comment by Barma-lej** [comment]
There is a new beta version [1.0.0b2](https://github.com/Barma-lej/landroid-card/releases/tag/1.0.0b2) here
