### ISSUE TITLE
v1.0.0 -  Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by ljmerza** [Barma-lej/landroid-card#264]
version 1.0.0 just released

```
landroid-card.js?hacstag=5100454891001:647 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title')
    at de.renderTipButton (landroid-card.js?hacstag=5100454891001:647:1013)
    at de.render (landroid-card.js?hacstag=5100454891001:881:22)
    at de.update (landroid-card.js?hacstag=5100454891001:1:15792)
    at de.performUpdate (landroid-card.js?hacstag=5100454891001:1:7103)
    at de.scheduleUpdate (landroid-card.js?hacstag=5100454891001:1:6750)
    at de._$Ej (landroid-card.js?hacstag=5100454891001:1:6658)
```
 at ```const a = G`<div .title="${i.title}: ${i.state}">```

config 

```
image: default
image_size: '4'
show_animation: true
show_status: true
show_toolbar: true
type: custom:landroid-card
entity: lawn_mower.david_mowie
camera: camera.mower_camera
show_name: true
compact_view: false

```

**Comment by Barma-lej** [comment]
What sensors do you have enabled?

**Comment by ljmerza** [comment]
![20240111_182822479.png](https://github.com/Barma-lej/landroid-card/assets/4085765/d60fda59-b68a-412e-8b07-834efa922810)

![20240111_182802615.png](https://github.com/Barma-lej/landroid-card/assets/4085765/f4798275-6135-4559-904e-19ed35f9ac51)

**Comment by Barma-lej** [comment]
In release note: "Please enable sensors at least `sensor.[mower_name]_rssi`, `sensor.[mower_name]_total_worktime` and `sensor.mower_battery` for correct work."
Please enable `sensor.[mower_name]_total_worktime`.

In future releases I will check for this error.
