### ISSUE TITLE
1.0.0 and 1.0.1 break Home Assistant update dialog

### ISSUE THREAD

**Issue by JurajNyiri** [Barma-lej/landroid-card#269]
## **Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser. [See here](https://github.com/Barma-lej/landroid-card/issues/3#issuecomment-1176298240)

## **Describe the bug**

Update to 1.0.0 and 1.0.1 breaks the Home Assistant update dialog.

## **Steps to reproduce**

1. Update to 1.0.1 or 1.0.0
2. Click on any update entity under Settings
3. There are no buttons to skip / update

## **Expected behavior**

Buttons to skip/update are visible.

## **Log, errors**

When I click on update entity I get following errors in console log in browser:

```

Failure writing unhandled promise rejection to system log: Error: Cannot parse given Error object
    at Object.parse (error-stack-parser.js:35:23)
    at stacktrace.js:106:62
    at new Promise (<anonymous>)
    at fromError (stacktrace.js:105:20)
    at t (log-message.ts:37:31)
    at logging-mixin.ts:66:33
(anonymous) @ logging-mixin.ts:77

```

```
Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-linear-progress" has already been used with this registry
```

These errors are not present when using the old version before 1.0.0.

## **Screenshots**

Before:

<img width="600" alt="Screenshot 2024-01-14 at 18 31 10" src="https://github.com/Barma-lej/landroid-card/assets/5785999/54f40c42-b11d-4f56-965c-3b717c508ab2">

After:

<img width="607" alt="Screenshot 2024-01-14 at 18 29 55" src="https://github.com/Barma-lej/landroid-card/assets/5785999/1954c99a-273e-4983-80f5-7cb3630bf554">

## **Versions:**

- Release: 1.0.1
- Browser: Chrome, Firefox
- HomeAssistant version: 2024.1.1, 2024.1.2, 2024.1.3
- Landroid_cloud integration N/A

**Comment by Barma-lej** [comment]
I removed the progress bar from the card in [version 1.0.2](https://github.com/Barma-lej/landroid-card/releases/tag/1.0.2).
This week I will try to solve the problem

**Comment by JurajNyiri** [comment]
I confirm the issue is no longer present in 1.0.2. Thank you!
