### ISSUE TITLE
PopUp at „Rain Delay“ and „Zone einstellen“ Wrong link

### ISSUE THREAD

**Issue by Cosmicbase** [Barma-lej/landroid-card#275]
## **Describe the bug**

Set the wrong link in Rain Delay and Zone

## **Steps to reproduce**

1. Go to Landroid Card
2. Click on the Tool Button on the right side of mowing and edge cutting area.
3. See the error when you Click on „Zone“ and „Rain Delay“  button.

## **Expected behavior**

A popup opens with a washing machine.
You would actually have a popup with the entity of Zone or Expect Rain Delay.

## **Screenshots**
![IMG_0571](https://github.com/Barma-lej/landroid-card/assets/31271212/18ad4257-5abf-41c0-b2a9-ae55d3021f9a)
![IMG_0572](https://github.com/Barma-lej/landroid-card/assets/31271212/c99ea207-5825-4d16-ae2a-bed96503f1c5)

## **Versions:**

- Release: [1.0.3]
- Browser: [safari]
- HomeAssistant version: [11.4]
- Landroid_cloud integration [v4.0.1]

@Barma-lej Of course, you can also write to me in German.

**Comment by Barma-lej** [comment]
Since the Landroid Cloud integration does not provide any entity for configuring Rain Delay and Zone, to use the standard Input Select, I had to substitute the first one found in Home Assistant input_select. I hope that in future versions of Landroid Cloud, @MTrab will add entities that allow changing these settings, and then I will adapt the map accordingly.

**Comment by Guenni75** [comment]
Hallo.

![image](https://github.com/Barma-lej/landroid-card/assets/14917841/9e700308-79aa-4306-a8db-ac3517f5bc94)

Wenn ich es richtig verstehe, sind diese "Entity nicht verfügbar" Fehler genau das Problem hier, oder?

**Comment by maijo366** [comment]
How can i set this error with set zone/Raindelay?? Script?
I have the same error in this card.
![grafik](https://github.com/Barma-lej/landroid-card/assets/96180786/80f6df9e-6228-400b-8f6f-6c7a0f8b8854)

Many thanks for helping ;-)

**Comment by Barma-lej** [comment]
Read please [here](https://github.com/Barma-lej/landroid-card?tab=readme-ov-file#known-issues)
If you want to show these entities, please create a temporary `input_select` in your configuration:
```
input_select:
  landroid_temp:
    options:
      - temp
```
Ist es nicht zu früh, um zu mähen?

**Comment by Cosmicbase** [comment]
> Ist es nicht zu früh, um zu mähen?

Also mein Mäher fährt auch schon, wir haben 18°C heute.

**Comment by Cosmicbase** [comment]
> Read please [here](https://github.com/Barma-lej/landroid-card?tab=readme-ov-file#known-issues)
> If you want to show these entities, please create a temporary `input_select` in your configuration:

Can you give a specific example so that everyone can use it?
Where must

`input_select:
  landroid_temp:
    options:
      - temp`
 
be inserted?

**Comment by Barma-lej** [comment]
Check this [article](https://www.home-assistant.io/integrations/input_select/)
You can use two ways:
1. Via the user interface (preffered)
2. Via `configuration.yaml`

> 18°C heute.
 
Ja, aber:

![Screenshot_20240320_134118_Weather Radar Pro](https://github.com/Barma-lej/landroid-card/assets/34010886/80a08b53-de57-4d1e-8b90-8122f3faa2b6)

**Comment by maijo366** [comment]
Is it now possible with the new updated integration 5.0.1 to set the zones?

**Comment by Barma-lej** [comment]
Yes, it's already in progress
