### ISSUE TITLE
Replace the picture of the mower with your own.

### ISSUE THREAD

**Issue by Cosmicbase** [Barma-lej/landroid-card#288]
Can you offer a way to swap the 2-color image of the mower into your own image?
Maybe the link to the image in Landroid-Card.js.
This Picture is only an example.

![Toadie](https://github.com/Barma-lej/landroid-card/assets/31271212/63a21f79-6028-4a4c-ae45-dfca97612ccc)

**Comment by Barma-lej** [comment]
Please read the [Manual](https://github.com/Barma-lej/landroid-card?tab=readme-ov-file#usage) - option `image`

**Comment by Cosmicbase** [comment]
Thank you, just image under /local/pictures/xxx.png (.svg)
and image: change default.
It looks good.

type: vertical stack
     cards:
          
       - type: custom:landroid-card
        entity: lawn_mower.mower
        image: /local/pictures/Toadie-removebg-preview.png
        compact_view: false
        show_name: true
        show_status: true
        show_configbar: true
        show_toolbar: true
        stats:
          default:
            - entity_id: sensor.mower_blades_total_on_time
              unit: h
              subtitle: Gesamt Klingenlaufzeit
              value_template: '{{ as_timedelta((value | float(0) * 3660) | string) }}'
            - entity_id: sensor.mower_blades_current_on_time
              unit: h
              subtitle: Klingenlaufzeit aktuell
              value_template: '{{ as_timedelta((value | float(0) * 3660) | string) }}'
            - entity_id: sensor.mower_total_worktime
              unit: h
              subtitle: Laufzeit total
              value_template: '{{ as_timedelta((value | float(0) * 3660) | string) }}'
            - entity_id: sensor.mower_distance_driven
              value_template: '{{ (value | float(0) / 1000) | round(3) }}'
              unit: km
              subtitle: Distanz
          mowing:
            - attribute: orientation.yaw
              subtitle: Yaw
              unit: °
            - attribute: orientation.roll
              subtitle: Roll
              unit: °
            - attribute: orientation.pitch
              subtitle: Pitch
              unit: °
        shortcuts:
          - name: Benachrichtigung
            service: automation.toggle
            icon: mdi:bell
            service_data:
              entity_id: automation.mower_notify_status

![Toadie](https://github.com/Barma-lej/landroid-card/assets/31271212/bcc611bd-26e5-419a-a5bf-4a95e372a772)
