### ISSUE TITLE
Animation seems to be broken

### ISSUE THREAD

**Issue by Skyber1967** [Barma-lej/landroid-card#30]
## **Before submitting a bug**

[ *] I updated to the latest version available
[* ] I cleared the cache of my browser

Just updated to last version and animation seems to be broken, is it me or a bug ?

## **Versions:**

- Release: 0.2.2

**Comment by Barma-lej** [comment]
Is the animation on in config?

**Comment by Skyber1967** [comment]
Yes,
![image](https://user-images.githubusercontent.com/102285630/182176091-807f24fd-2fe6-4d14-918f-0447431cf5c6.png)

**Comment by Barma-lej** [comment]
Fixed in [0.2.3](https://github.com/Barma-lej/landroid-card/releases/tag/0.2.3)

**Comment by Skyber1967** [comment]
Sorry but no success for me. refreshed (ctrl F5) + reboot HA.

**Comment by Barma-lej** [comment]
Can you publish error in [the console of the browser's debugger](https://javascript.info/debugging-chrome#console)

**Comment by Skyber1967** [comment]
Ok solved, ctrlF5 was not enough, I cleared data in Chrome and animation is now working.

Sorry for that ;)
