### ISSUE TITLE
Card didnt show all values

### ISSUE THREAD

**Issue by Sting2saw** [Barma-lej/landroid-card#301]
Before submitting a bug
[x ] I updated to the latest version available
[x ] I cleared the cache of my browser

Describe the bug
My Card is not fully working, there are many stats that wont show up like, Wifi, Battery, Blades state etc.

Steps to reproduce
Just updated the mower card, after Winter.

Expected behavior
it looks like there is still an Old version of this Card in my config, but i dont know why. I deleted the .js file and replaced it with the new one from 1.0.4

Screenshots
ignore the error, that comes from clogged Blades:
Landroid Cloud is working fine and i have all the entities enabled that would be needed for the Card, but the Card didnt show them.
Any ideas?
![mower](https://github.com/Barma-lej/landroid-card/assets/109652016/7c38a6f9-80d5-4caa-a3ab-5ed275f71dd3)

Versions:
Release: [ 1.0.4]
Browser: [Chrome]
HomeAssistant version: [ newes]
Landroid_cloud integration [ 4.0.3]

**Comment by Barma-lej** [comment]
You need to remove browser cache

**Comment by Sting2saw** [comment]
omg i tought i did with the Strg + F5 Combo, but a real Browser Cache delete worked, thanks alot!
