### ISSUE TITLE
Wrong Data on Wifi, Stat and battery subviews

### ISSUE THREAD

**Issue by Levante75** [Barma-lej/landroid-card#303]
Hi all, first:Thanks for the good work!
I wonder what is wrong, maybe my fault...
Have Landroid Cloud version 4.0.2
Landroid Card 1.0.4
Core 2024.3.3
Supervisor 2024.03.0
Operating System 12.1
Frontend 20240307.0
All sensors from Landroid Cloud enabled, showing correct data.
When clicking on the upper icons get wrong data

![image](https://github.com/Barma-lej/landroid-card/assets/63196199/686561bd-e38f-47fb-8532-052a143a7276)

**Comment by Barma-lej** [comment]
Please read #301
and
[ ] I cleared the cache of my browser. [See here](https://github.com/Barma-lej/landroid-card/issues/3#issuecomment-1176298240)

**Comment by Levante75** [comment]
Hi, thank you. Tried it but without succes. Now I'm completely lost. I started all over
**landroid-card.js is in;**
![image](https://github.com/Barma-lej/landroid-card/assets/63196199/fc195cbb-bf13-4761-b45c-8f15ec484e28)
**Entry in resources is:**
![image](https://github.com/Barma-lej/landroid-card/assets/63196199/86ebd3f9-4926-446d-8082-2fce0e935bac)
**Adding a card:**
![image](https://github.com/Barma-lej/landroid-card/assets/63196199/effeb1c3-13f1-4b4a-94ac-bbddc5c2c89f)
**Mower does not appear in the entity list box, So passed to the code editor and added my robot manually:
Nothing appears in the card.**
![image](https://github.com/Barma-lej/landroid-card/assets/63196199/afea3da0-c2e3-4f5c-b3cc-44c8ccfcdcaf)
Looks like my robot is not recognised by the card as a lan mower.
What to do next?

**Comment by Barma-lej** [comment]
On your  first screenshot card version is < 1.0.0. So you need to clear the cache.
Did you install the card with HACS or manual?
How many `landroid-card.js` records do you have in resources https://my.home-assistant.io/redirect/lovelace_dashboards/

**Comment by Levante75** [comment]
Cleared Cache by right-mouse inspect, refresh clear cache and force reload
I installed manual, was not showing up in HACS
So downloaded landroid-card.js from 1.0.4 feb 2
Only one landroid-card.js in resources.
For test tried with the vacuum-card and works,

**Comment by Levante75** [comment]
Hey, It is working!  Do not know wat I exactly did
![image](https://github.com/Barma-lej/landroid-card/assets/63196199/ae60665a-547e-40f2-be31-69b0643ae2f0)
Thank you for your patience!
