### ISSUE TITLE
Replace action object not working

### ISSUE THREAD

**Issue by Kejszijo** [Barma-lej/landroid-card#304]
Hi,

I try to replace the default start and edgecut action button, but, with this code not working. It's start the default start routine. I used this with the previous card (0.3.2), and it was worked.

>     actions:
>       start:
>         service: script.mower_start_mow
>       edgecut:
>         service: script.mower_start_cut_to_edge
>     shortcuts:
>       - name: Teszt
>         service: script.mower_start_mow
>         icon: mdi:bell

With "Teszt" button works fine.

I cleared the cache of my browser, but no change.

- Release: [1.0.4]
- Browser: [chrome]
- HomeAssistant version: [2024.3.3]
- Landroid_cloud integration [4.0.3]

**Comment by Barma-lej** [comment]
I'm sorry.
I forgott to describe [new actions objects](https://github.com/Barma-lej/landroid-card?tab=readme-ov-file#actions-object).
New actions are `start_mowing`, `edgecut`, `pause` and `dock`

**Comment by Kejszijo** [comment]
Thanks, it's work fine now! :)
