### ISSUE TITLE
no attribut timeextension on wr142e

### ISSUE THREAD

**Issue by user86000** [Barma-lej/landroid-card#305]
**Is your feature request related to a problem? Please describe.**
WR142 has no attribute timextension, so the slider in configuration doesn't work

**Describe the solution you'd like**
i want a possibibility to hide unneeded attributes/entities in settings

**Additional context**
![image](https://github.com/Barma-lej/landroid-card/assets/122205057/f31a4b01-f65c-4427-86af-a72c7d2e7a20)
![image](https://github.com/Barma-lej/landroid-card/assets/122205057/ff99a468-c889-4bd3-95fb-7be06a45bcb5)

**Comment by Barma-lej** [comment]
[See here](https://github.com/MTrab/landroid_cloud/issues/493)

**Comment by user86000** [comment]
Newer mower like wr142e (m700) don't have this parameter.
Thats the reason why it's better to remove this setting from the card

if i change the working time in the android landroid app it changes the daily end time directly

![image](https://github.com/Barma-lej/landroid-card/assets/122205057/2fe9a997-e4cd-4215-966c-3f39258f21fc)

**Comment by Barma-lej** [comment]
> Newer mower like wr142e (m700) don't have this parameter.

My WR141E lawnmower had this attribute.

> Thats the reason why it's better to remove this setting from the card

You don't have to use this setting. But I still hope that @MTrab will find a way to create the necessary sensors.

**Comment by Barma-lej** [comment]
This issue is already described in the readme file in the [Known issues](https://github.com/Barma-lej/landroid-card?tab=readme-ov-file#known-issues) section.

**Comment by user86000** [comment]
i don't like not-working-parameters in cards.

So i have to build my own card (stacks, conditions, picture card) or clone and modify the card myself.

this was not a bug report, it was a feature request to hide unwanted / unused options
