### ISSUE TITLE
Change timeformat to local timeformat

### ISSUE THREAD

**Issue by Danit2** [Barma-lej/landroid-card#31]
First of all. I like your new added `next_scheduled_start`

**Is your feature request related to a problem? Please describe.**
it would be great if the date and time format could be adapted to the local date and time format.

**Describe the solution you'd like**
in the editor the possibility to change the date and time format

**Describe alternatives you've considered**
the card automatically adapts the date and time format to the format set in the home assistant.

**Additional context**
the current date and time format is the american format and not the european one.

**Comment by luzik** [comment]
It is also related to last updated date time

**Comment by Dielee** [comment]
![2023-04-25 07_49_18-Übersicht – Home Assistant](https://user-images.githubusercontent.com/45101649/234185627-5ab1e242-d996-4596-81c5-12b85ff9b6fc.png)
@Barma-lej please release a new version. I have built your changes by myself with rollup and it works perfectly.

**Comment by Barma-lej** [comment]
i hope its fixed in https://github.com/Barma-lej/landroid-card/releases/tag/0.2.5
