### ISSUE TITLE
Invisible card on IOS app

### ISSUE THREAD

**Issue by Driekes** [Barma-lej/landroid-card#32]
## **Before submitting a bug**

[ ] I updated to the latest version available
[ ] I cleared the cache of my browser

## **Describe the bug**

The card is invisible on the iPhone, even if I close the app, or pull down to refresh the dashboard. I only have a 'Rain delay (undefined min), so maybe there is something wrong in another area and causing this.

## **Steps to reproduce**

Go to the tab where you added the card. It works on the browser on Ios, other apps, but it is not visible on iOS app in my case. Don't know how to force refresh or force it to show. I did sometimes have the idea that it starts to be visible as soon as the mower is running or changes state.

## **Expected behavior**

Card is there.

## **Versions:**

- Release: .2.3.
- Browser: iOS app
- HomeAssistant version: 2022.7.6
- Landroid_cloud integration 2.3.1

**Comment by Driekes** [comment]
Nevermind, I did find the 'reset frontend cache' option in the app settings, that resolved it. Let's see how long it stays this way, otherwise I might open this ticket again.

**Comment by Barma-lej** [comment]
What is your installation method? There were no problems with the HACS method, only manually

**Comment by Driekes** [comment]
Install method was HACS. It showed and disappeared regularly on iOS app. I will keep you updated.
