### ISSUE TITLE
Party Mode status with main icon or as a label in the status.

### ISSUE THREAD

**Issue by Mincka** [Barma-lej/landroid-card#321]
**Is your feature request related to a problem? Please describe.**
When I have a look at the card, I cannot tell if Party Mode is enabled without opening the settings.
Since I see the date of the next schedule, I believe that the mower will start, but this is "misleading" since "Party Mode" is enabled.

**Describe the solution you'd like**
- Show the Party Mode icon as one of the main icons of the card.
- Alternatively, show "Docked (Party Mode)" instead of just "Docked". 

**Describe alternatives you've considered**
Use a custom stacking card to combine this card with a entity card just to show the "Party Mode".

**Additional context**
Tested on landroid-card master (daaa172) with Landroid Cloud 5.0.2.

**Comment by Cosmicbase** [comment]
When is the fix coming?

**Comment by Mincka** [comment]
Thanks a lot @Barma-lej! I sent you coffees. ☕ 

@Cosmicbase: [build it yourself](https://github.com/Barma-lej/landroid-card/blob/master/CONTRIBUTING.md#how-to-run-locally) if you cannot wait for the next release.
