### ISSUE TITLE
blade running time misrepresented

### ISSUE THREAD

**Issue by Cosmicbase** [Barma-lej/landroid-card#341]
## **Describe the bug**

Blade runtime is displayed incorrectly instead of factor 1 is divided by 1000 in the YAML

## **Steps to change and solve the problem**

Change divided 1000 to factor 1

## **Versions:**

- Release: 1.1.0
- HomeAssistant version: 2024.4.3
- Landroid_cloud integration 4.0.2

![IMG_1075](https://github.com/Barma-lej/landroid-card/assets/31271212/29ee624f-dd14-49fc-b5c4-72b204640463)
![IMG_1074](https://github.com/Barma-lej/landroid-card/assets/31271212/c29c4134-979c-4228-8533-74a4fc7ea2e2)

**Comment by Barma-lej** [comment]
I use:
```
    - entity_id: sensor.mower_blades_total_on_time
      subtitle: Total blade time
      value_template: '{{ as_timedelta((value | float(0) * 3600) | string) }}'
    - entity_id: sensor.mower_blades_current_on_time
      subtitle: Current blade time
      value_template: '{{ as_timedelta((value | float(0) * 3600) | string) }}'
    - entity_id: sensor.mower_total_worktime
      subtitle: Work time
      value_template: '{{ as_timedelta((value | float(0) * 3600) | string ) }}'
    - entity_id: sensor.mower_distance_driven
      value_template: '{{ (value | float(0) / 1000) | round(3) }}'
      unit: km
      subtitle: Distance
```

**Comment by Cosmicbase** [comment]
value_template: '{{ as_timedelta((value | float(0) * 3600) | string) }}'
    - entity_id: sensor.mower_blades_current_on_time
      subtitle: Current blade time
      

Multiplier 3600 is too much. I get the wrong value. If I only use 1, i.e. don't multiply, the result is perfect.

For the other calculations I used /1000 instead of * 3600. All values ​​match the app.

![IMG_1082](https://github.com/Barma-lej/landroid-card/assets/31271212/dc8d23ff-167d-45e3-8404-990ea1f43025)
![IMG_1081](https://github.com/Barma-lej/landroid-card/assets/31271212/b4af22a1-0f2d-45b1-b094-7af73369d710)

**Comment by Barma-lej** [comment]
Try it. It's cool. Just try )
