### ISSUE TITLE
Remove border from card with CSS?

### ISSUE THREAD

**Issue by joasag** [Barma-lej/landroid-card#342]
I am trying to remove the border with card-mod CSS. But I cannot manage to do it. I know it is border-style: none;
Tried using 
`        :host {
          border-style: none!important;
        }`

And read the readme, but there is no border --lc customization.

Any idea how to do it?

**Comment by Barma-lej** [comment]
Try to use `--ha-card-border-color` or `--divider-color` to change color of border
