### ISSUE TITLE
Status text shows Dutch translation and original text

### ISSUE THREAD

**Issue by Waling1961** [Barma-lej/landroid-card#343]
Status text shows Dutch translation and original text. Would like to see just the translation here.
![Mover translation](https://github.com/Barma-lej/landroid-card/assets/62181652/bd4d3b49-c8d6-4057-81fe-ff28ebfe41f8)

**Comment by Barma-lej** [comment]
it will be in version 1.1.1

**Comment by Waling1961** [comment]
Ok. Thanks
