### ISSUE TITLE
not all functions of landroid card are working fine

### ISSUE THREAD

**Issue by tomass0328** [Barma-lej/landroid-card#347]
I guess I'm doing something wrong. My landroid card is working only partially - it is showing some info about mower current status, blade time, distance etc in the card itself, but if you click on battery or wifi for more info so it is showing "-" or "0". Time shown in card is also incorrect (reset time, next scheduled time, etc). Also not all buttons are working, some of them are saying "service ... not found" if you click on them. Just to note - all possible mower entinties are enabled and working fine if you are checking them separately but not in landroid card.
I'm using landroid card version 1.1.0, landroid cloud version 5.0.2, landroid model "Landroid M700 (WR142E)".

![1](https://github.com/Barma-lej/landroid-card/assets/110176293/42d4d3a1-ceab-46f8-9b5c-4c43e4640b55)
![2](https://github.com/Barma-lej/landroid-card/assets/110176293/2709c110-6451-4657-bdd5-5185c1b78ca8)
![3](https://github.com/Barma-lej/landroid-card/assets/110176293/6f62e07f-ba01-47f7-bbf0-cf2ccc4b5980)
![4](https://github.com/Barma-lej/landroid-card/assets/110176293/8f22b946-681c-4703-9524-e96fc2e6b271)
![5](https://github.com/Barma-lej/landroid-card/assets/110176293/8c96e837-4188-49f6-8340-4a71a4da2ead)

**Comment by Barma-lej** [comment]
Version landroid card

**Comment by tomass0328** [comment]
if you are asking for landroid card version so its 1.1.0. But I was writing this info already in my original message

**Comment by Barma-lej** [comment]
But i see an old version of the card. Can you show me home assistant resources:

[![Open your Home Assistant instance and show your resources.](https://my.home-assistant.io/badges/lovelace_resources.svg)](https://my.home-assistant.io/redirect/lovelace_resources/)

**Comment by tomass0328** [comment]
there are 2 entries related to landroid in resources:
/hacsfiles/landroid-card/landroid-card.js?hacstag=510045489110
/local/landroid-card.js

**Comment by Barma-lej** [comment]
you need to remove this entry:
`/local/landroid-card.js`

**Comment by tomass0328** [comment]
great, now its working!
Thanks!
