### ISSUE TITLE
<Integration Barma-lej/landroid-card> Repository structure for 1.1.1 is not compliant

### ISSUE THREAD

**Issue by johanberglin** [Barma-lej/landroid-card#361]
## **Before submitting a bug**

[x ] I updated to the latest version available
[x ] I cleared the cache of my browser. [See here](https://github.com/Barma-lej/landroid-card/issues/3#issuecomment-1176298240)

## **Describe the bug**

Whan adding custom repository to HACS i get this error
<Integration Barma-lej/landroid-card> Repository structure for 1.1.1 is not compliant

**Comment by mr-gosh** [comment]
You have to select "lovelace" as the repository straucture - than you can add it
![grafik](https://github.com/Barma-lej/landroid-card/assets/3028703/a50fd451-7d5e-4281-8d1d-e19151022ef9)

Than you can install it from the HACS Store

**Comment by johanberglin** [comment]
Thanks you can close this!

**Comment by johanberglin** [comment]
Thanks! Missed that. Closing
