### ISSUE TITLE
Card: Torque adjustment is unavailable

### ISSUE THREAD

**Issue by maijo366** [Barma-lej/landroid-card#374]
In my Landroid Card is the Torque adjustment unavailable.

![grafik](https://github.com/Barma-lej/landroid-card/assets/96180786/98a4eec8-da79-4483-b64c-46f89daffd5e)

In developertools:

![grafik](https://github.com/Barma-lej/landroid-card/assets/96180786/a67d1813-f16b-4121-bc65-7ec95cfb9b73)

- Release: [1.1.1]
- Browser: [firefox]
- HomeAssistant version: [2024.5.5]
- Landroid_cloud integration [5.0.5]

**Comment by Barma-lej** [comment]
@MTrab since version 5.0.3 Landroid_Cloud has temporarily disabled Torque entity.
I use 5.0.2
https://github.com/MTrab/landroid_cloud/releases/tag/v5.0.3

**Comment by MTrab** [comment]
Torque is disabled due to a firmware bug on some models, resulting in the mower crashing and no longer reporting states to the API until it has been restarted.
I'm awaiting Positecs take on this and a potential firmware update

**Comment by maijo366** [comment]
Thanks i don´t need this, but how can i this entity cancel from the card?

**Comment by Barma-lej** [comment]
This is not possible yet, but I plan to make separate settings for this, when I have time.
