### ISSUE TITLE
Installation over HACS

### ISSUE THREAD

**Issue by GreatEMU** [Barma-lej/landroid-card#385]
Sorry for this question, but I'm new to Home Assistant.
I allready installed HACS. But I can't find this card.

## **Before submitting a bug**

[ ] I updated to the latest version available
[ ] I cleared the cache of my browser. [See here](https://github.com/Barma-lej/landroid-card/issues/3#issuecomment-1176298240)

## **Steps to reproduce**

3. See error

## **Log, errors**

Error in the log of Home Assistant: **Settings -> System -> Logs**
[Error in browser debugger console](https://javascript.info/debugging-chrome#console)

## **Screenshots**

For example, JavaScript errors are shown [in the browser's web inspector](https://javascript.info/debugging-chrome#console) (if applicable).

## **Versions:**

- Release: [e.g. 0.2.0]
- Browser: [e.g. chrome, safari]
- HomeAssistant version: [e.g 2022.8.0]
- Landroid_cloud integration [e.g 2.3.0]

**Comment by Barma-lej** [comment]
You need to add the __*https://github.com/Barma-lej/landroid-card*__ repository to HACS. As described here:  https://hacs.xyz/docs/faq/custom_repositories/

Repository: https://github.com/Barma-lej/landroid-card
Category: Lovelace

**Comment by GreatEMU** [comment]
Thanks!

Now I want to configure the card.
I have to select an entity. But the is no one shown.
Do I miss anything?

**Comment by Barma-lej** [comment]
What kind of the lawn mower do you have? entity_id?

**Comment by GreatEMU** [comment]
Thank you for your quick reply.

I have a Worx WR165E.

![image](https://github.com/user-attachments/assets/43120f4f-16a3-45c6-8af6-f157eb32d73b)


Update!
I managed it my using the Code Editor.

**Comment by Barma-lej** [comment]
Please read carefully at first here https://github.com/Barma-lej/landroid-card?tab=readme-ov-file#requirements
Then here https://github.com/MTrab/landroid_cloud
Then https://github.com/Barma-lej/landroid-card?tab=readme-ov-file#installation

**Comment by GreatEMU** [comment]
Everything is new for me... 😩

I did everything as described, except the enablation of the sensors. Where do I have to do this?
Am I right that I have to code all processing with the mover by my own? Or where I have to put in my login?

**Comment by Barma-lej** [comment]
You must have an entity_id in the domain _lawn_mower_. Do you have an entity with name _lawn_mower.NAME_OF_YOUR_LAWNMOWER_?

**Comment by GreatEMU** [comment]
How can I have an entity of my mower if I have not entered my login details anywhere?
This was my question before. Where do I have to enter my login?

**Comment by GreatEMU** [comment]
Got it!
I just forgot to add the integration.
Reminder to me: It is not enough to install the integration!
