### ISSUE TITLE
Card is blank / not displayed 

### ISSUE THREAD

**Issue by ajb538** [Barma-lej/landroid-card#394]
Cache has been cleared.

Unable to view the card (shows a blank card).  Using Chrome browser. 

## **Expected behavior**

Card to display!

## **Log, errors**

Error captured in logs:

Logger: frontend.js.latest.202407100
Source: components/system_log/__init__.py:333
First occurred: 12:05:48 PM (16 occurrences)
Last logged: 12:44:15 PM

Uncaught error from Chrome 126.0.0.0 on Mac OS 10.15.7 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "landroid-card-editor" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /local/landroid-card.js:1:181307
Uncaught error from Chrome 126.0.0.0 on Mac OS 10.15.7 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "landroid-card-editor" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/landroid-card/landroid-card.js:1:191211
Uncaught error from Chrome 127.0.0.0 on Mac OS 10.15.7 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "landroid-card-editor" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/landroid-card/landroid-card.js:1:191211

## **Screenshots**
<img width="1201" alt="Screen Shot 2024-08-03 at 1 05 37 pm" src="https://github.com/user-attachments/assets/5f9cd3a2-4187-43d3-ba07-14f70546fa03">

Card is shown as entirely black under the vacuum cards in the above screenshot.

## **Versions:**

- Release: 1.1.1
- Browser: Chrome
- HomeAssistant version: 2024.7.4
- Landroid_cloud integration 5.0.5

**Comment by ajb538** [comment]
note: I removed the card and files from config, re-added / downloaded. The cards show then briefly disappear.

**Comment by Barma-lej** [comment]
You have added the card twice. The first time via HACS, the second time manually.
You need to remove the manually added card from custom repositories

**Comment by ajb538** [comment]
Hi - only the one repo listed in custom repositories, so I'm not sure that is cause?

**Comment by Barma-lej** [comment]
From your log:
```
...
 /local/landroid-card.js
...
/hacsfiles/landroid-card/landroid-card.js
...
```
You have two instance of the landroid card

**Comment by ajb538** [comment]
thanks - hacsfiles is a symlink for 'www/community', and is the correct location for HACs install, correct?

I can't find another instance in the HA vm? I assume /local is usually a user home space, can't find such a folder? A search from the root folder only finds the one file in the www/community folder..

<img width="462" alt="Screen Shot 2024-08-05 at 9 12 05 am" src="https://github.com/user-attachments/assets/d4d158a2-8a36-4d60-91f2-d0e88a97a80e">


Thanks.

**Comment by Barma-lej** [comment]
/local is root of config/www
Can you publish content of custom repositories?
https://hacs.xyz/docs/faq/custom_repositories/

**Comment by ajb538** [comment]
<img width="314" alt="Screen Shot 2024-08-06 at 9 04 30 pm" src="https://github.com/user-attachments/assets/3fd9c78a-b761-4908-a58a-876e245db67d">

**Comment by Barma-lej** [comment]
Sorry for mistake
You need to remove the manually added card not from custom repositories but from resources
https://developers.home-assistant.io/docs/frontend/custom-ui/registering-resources/

**Comment by ajb538** [comment]
Hmm. I've gone backwards.... :)

I removed the repo and the resources (checked it removed the folder from www/ ). Re-installed and can see the folder added by HACs in config/www and the resource registered.

<img width="1147" alt="Screen Shot 2024-08-13 at 9 09 52 pm" src="https://github.com/user-attachments/assets/4a21f61f-5409-4b7c-855a-bcd1fe9d06ec">

But get 'custom element doesnt exist: landroid-card'. Which is weird, as it does! :) I've tried the usual cache clear etc..

Also isnt found when trying to add a new card etc...?

**Comment by Barma-lej** [comment]
Is the card installed in HACS? Please screenshot.

**Comment by ajb538** [comment]
hey - yes - I just removed again, cleared cache, and restarted for the 5th time and its appearing now! Weird. :) 

Thanks for your assistance - appreciated!

**Comment by ajb538** [comment]
(coffee bought - thanks for the help!)
