### ISSUE TITLE
French Support

### ISSUE THREAD

**Issue by Skyber1967** [Barma-lej/landroid-card#4]
Hi !

I just translated en.json to french (see attachement). Don't know how to add to your Github but attached in txt format.
Hope it's good for you to implement.
If you want, I can test it before publishing.

Fyi, card works also great with WR143 landroid model.

Great work !

[fr.txt](https://github.com/Barma-lej/landroid-card/files/9063580/fr.txt)

**Comment by Barma-lej** [comment]
Added and released [0.1.4](https://github.com/Barma-lej/landroid-card/releases/tag/0.1.4)
