### ISSUE TITLE
Only mower status of card translated to Hungarian

### ISSUE THREAD

**Issue by cinadr** [Barma-lej/landroid-card#415]
## **Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser. [See here](https://github.com/Barma-lej/landroid-card/issues/3#issuecomment-1176298240)

## **Describe the bug**

After updating card to latest and F12 - Clear and reload page in chrome, only the status of the mover translated to Hungarian.
I've also validated hu.json and its syntax is correct.

## **Steps to reproduce**

Open Lovelace card after changing HA language to Hungarian.

## **Expected behavior**

Show all translated strings in the card.

## **Log, errors**

Nothing relevant in HA/Chrome logs. Latter shows Landroid Vard 1.1.3 loaded.

## **Screenshots**

![chrome_PdqlQlkali](https://github.com/user-attachments/assets/9a258ca3-59d2-4a63-b9f6-7bd6db9f14ca)

## **Versions:**

- Release: 1.1.3
- Browser: Google Chrome
- HomeAssistant version: 2024.10.1
- Landroid_cloud integration 5.0.6

**Comment by Barma-lej** [comment]
The names "Blades total on time", "Blades current on time", and other entity names are the default names in Home Assistant. You can customize these names directly in Home Assistant by following the instructions here: https://www.home-assistant.io/docs/configuration/customizing-devices/.
