### ISSUE TITLE
no torque availible

### ISSUE THREAD

**Issue by Cosmicbase** [Barma-lej/landroid-card#468]
## **Describe the bug**

no torque availible

settings:
          - switch.mower_party_mode
          - switch.mower_locked
          - number.mower_raindelay
          - number.mower_time_extension
          - number.mower_torque  **Is missing at the moment**
          - select.mower_current_zone
          - button.mower_start_cutting_edge
          - button.mower_restart_baseboard

## **Screenshots**

![torque](https://github.com/user-attachments/assets/dcd02e55-55ca-4702-865f-6a5af505c453)

## **Versions:**

- Release: [1.2.1]
- HomeAssistant version: [2024.10.4]
- Landroid_cloud integration [v 5.1.0]

**Comment by Barma-lej** [comment]
If you don't have an entity, just remove it from the configuration.

**Comment by Barma-lej** [comment]
Please post your whole configuration, why is your mower named `Toadie` and your entities named `mower`? Did you rename these entities from `switch.toadie_party_mode` to `switch.mower_party_mode`?

**Comment by Cosmicbase** [comment]
- type: vertical-stack
    cards:
          
      - type: custom:landroid-card
        entity: lawn_mower.mower
        image: /local/pictures/Toadwart.png
        compact_view: false
        show_name: true
        show_status: true
        show_configbar: true
        show_toolbar: true
        stats:
          default:
            - entity_id: sensor.mower_blades_total_on_time
              unit: h
              subtitle: Gesamt Klingenzeit
              value_template: '{{ ((value | float(0) / 1000) | round(3)) }}'
            - entity_id: sensor.mower_blades_current_on_time
              unit: h
              subtitle: Klingenzeit aktuell
              value_template: '{{ ((value | float(0) / 1) | round(3)) }}'
            - entity_id: sensor.mower_total_worktime
              unit: h
              subtitle: Laufzeit total
              value_template: '{{ (value | float(0) / 1000) | round(3) }}'
            - entity_id: sensor.mower_distance_driven
              value_template: '{{ (value | float(0) / 1000) | round(3) }}'
              unit: km
              subtitle: Distanz
          mowing:
            - entity_id: sensor.mower_yaw
              subtitle: Yaw
              unit: °
            - entity_id: sensor.mower_roll
              subtitle: Roll
              unit: °
            - entity_id: sensor.mower_pitch
              subtitle: Pitch
              unit: °
        settings:
          - switch.mower_party_mode
          - switch.mower_locked
          - number.mower_raindelay
          - number.mower_time_extension
          - number.mower_torque
          - select.mower_current_zone
          - button.mower_start_cutting_edge
          - button.mower_restart_baseboard

**Comment by Cosmicbase** [comment]
- type: custom:landroid-card
        entity: lawn_mower.mower
        image: /local/pictures/Toadwart.png
        compact_view: false
        show_name: true
        show_status: true
        show_configbar: true
        show_toolbar: true
        stats:
          default:
            - entity_id: sensor.mower_blades_total_on_time
              unit: h
              subtitle: Gesamt Klingenzeit
              value_template: '{{ ((value | float(0) / 1000) | round(3)) }}'
            - entity_id: sensor.mower_blades_current_on_time
              unit: h
              subtitle: Klingenzeit aktuell
              value_template: '{{ ((value | float(0) / 1) | round(3)) }}'
            - entity_id: sensor.mower_total_worktime
              unit: h
              subtitle: Laufzeit total
              value_template: '{{ (value | float(0) / 1000) | round(3) }}'
            - entity_id: sensor.mower_distance_driven
              value_template: '{{ (value | float(0) / 1000) | round(3) }}'
              unit: km
              subtitle: Distanz
          mowing:
            - entity_id: sensor.mower_yaw
              subtitle: Yaw
              unit: °
            - entity_id: sensor.mower_roll
              subtitle: Roll
              unit: °
            - entity_id: sensor.mower_pitch
              subtitle: Pitch
              unit: °
        settings:
          - switch.mower_party_mode
          - switch.mower_locked
          - number.mower_raindelay
          - number.mower_time_extension
          - number.mower_torque
          - select.mower_current_zone
          - button.mower_start_cutting_edge
          - button.mower_restart_baseboard



![toadie](https://github.com/user-attachments/assets/d84299d8-f5bc-4ed3-938f-f310d9cd8077)

**Comment by Barma-lej** [comment]
Do you have `number.mower_torque` entity in your Home Assistant? If you don't have this entity, just remove it from the configuration.

**Comment by Cosmicbase** [comment]
> Do you have `number.mower_torque` entity in your Home Assistant? If you don't have this entity, just remove it from the configuration.

Unfortunately, the entity was no longer integrated after landroid cloud v5.0.2. 
Too bad, maybe I have to inform @MTrab
