### ISSUE TITLE
Incorrect time format for stats

### ISSUE THREAD

**Issue by Papi77** [Barma-lej/landroid-card#5]
## **Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

## **Describe the bug**

The time format of the stats values (total blade time, current blade time, etc. shows long time format with days and time in one line).

## **Expected behavior**

Stats time should be able to be displayed in two lines (e.g. days and hours) or in smaller font text or in hours only.

## **Screenshots**

![image](https://user-images.githubusercontent.com/26800136/177796252-05eb4b9e-f3cf-450b-8b8c-47a2e93fdae2.png)

## **Versions:**

- Release: [e.g. 0.1.3]
- Browser: [e.g. Firefox]
- HomeAssistant version: [e.g 2022.7]

**Comment by Papi77** [comment]
Sorry, this is probably not a bug but a feature enhancement only!

**Comment by Barma-lej** [comment]
[See you here](https://github.com/Barma-lej/landroid-card/tree/master#stats-object) for manual.
You can change the format as you wish.

**Comment by Barma-lej** [comment]
These are statistics and should be read:
Total blade time is 9 days and 14 hours and 49 minutes.
But as I said, you can make any format you want. [Here is Home Assistant Templating](https://www.home-assistant.io/docs/configuration/templating/#time)

**Comment by Papi77** [comment]
Got it, thanks!
