### ISSUE TITLE
Add "Return to base" button

### ISSUE THREAD

**Issue by denniz89** [Barma-lej/landroid-card#54]
**Is your feature request related to a problem? Please describe.**
I can't manually return the mower by the card

**Describe the solution you'd like**
I tried to read the command from the mower history and tried this:
shortcuts:
  - name: Zurück zur Ladestation
    service: vacuum.return_to_base
    icon: mdi:home

**Describe alternatives you've considered**
Tried "return_to_base", "vacuum.return_to_base" & "service.return_to_base"

**Additional context**
I'm pretty new to home assistant and still trying to get the overview of all functions to customize my cards

**Comment by Barma-lej** [comment]
When the mower is mowing, the "Return Home" button appears.
