### ISSUE TITLE
Adding more camera feeds

### ISSUE THREAD

**Issue by dersch81** [Barma-lej/landroid-card#55]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to add more camera feeds with a rolling change in the card. The garden is observed with a few cameras where the Landroid will be visible during the mowing process. I understand the camear feature is the best with a attached camera directly to the Landroid but that is a rare case i guess. By adding more than one camera to the card i will be able to observe the whole area where the Landroid will move.

**Comment by Barma-lej** [comment]
I think it is not worth implementing in the card what is not related to the mower, but to the surveillance

**Comment by dersch81** [comment]
In my case it is just related to the mower. Just one camera does not see
the moving mower all the time but some other cams can see it from different
angles. A rotation of cameras would see the whole mowing process.

Am Fr., 16. Sept. 2022 um 00:13 Uhr schrieb Barma-lej <
***@***.***>:
