### ISSUE TITLE
Landroid card shows different values then what the mover is doing

### ISSUE THREAD

**Issue by joernborup** [Barma-lej/landroid-card#56]
## **Before submitting a bug**

[ x] I updated to the latest version available
[ x] I cleared the cache of my browser. [See here](https://github.com/Barma-lej/landroid-card/issues/3#issuecomment-1176298240)

## **Describe the bug**
The Landroid-card shows different values then what the Landroid app and the mover is doing.
Like - the card shows that the mover is Mowing and it has 23% power - when it is actually docked with full power. The native Landroid app shows docked with 100%.

. 
## **Steps to reproduce**
Just installed latest.
Both card and integration.

## **Expected behavior**
Show same values as native app.

## **Log, errors**
None

## **Screenshots**

For example, JavaScript errors are shown [in the browser's web inspector](https://javascript.info/debugging-chrome#console) (if applicable).

## **Versions:**
 Home Assistant 2022.9.2 
Supervisor 2022.08.6 
Operating System 8.5 
Frontend 20220907.0 - latest 

Browser: Firefox (mac), Fully Kiosk (tablet)
Landroid_cloud integration [ 2.3.1]
Card 0.2.3

**Comment by Barma-lej** [comment]
I think that's not a landroid card issue but either landroid_cloud integration or a browser/dashboard refresh issue.
Check mower's attributes when was the mower last update

**Comment by joernborup** [comment]
Hi
Time is now 12:35 16-09-2022
LoveLace UI (card/entity?) says for State update at september 15, 2022 at
11:13:42 AM
Landroid app says -Last update 16 sep 2022 at 12.34.41

so, guess that it is the landroid_cloud integration that is not getting the
latest status.

You can close this one. I will contact the landroid_cloud integration.

Thanks for you help and nice product ;-)

/Joern

**Comment by joernborup** [comment]
After unlinking in the mower as described in the landroid cloud, and adding again it seems fine.
;-)
