### ISSUE TITLE
Partyzone to toolbar - smaller icon ?

### ISSUE THREAD

**Issue by joernborup** [Barma-lej/landroid-card#57]
Nice Card for the Landroid.

The full card, with everything turned on, looks nice. But I would also like to 'monitor' the mower from a tablet with limited 'real estate' - so I have save the space.

![Screenshot 2022-09-16 at 15 22 56](https://user-images.githubusercontent.com/60480578/190649941-80e917df-ffc9-407d-b21d-25b96919080e.png)

I like the icon, that it shows that the mower is active - but it takes up to much space - maybe if the icon could be like a 3. in size ?

Would be nice to have the 'party' function added/moved to the toolbar. Then only one row is needed, and the functions that i need are there in one line - start, stop, home, party.

When there is only 1 zone defined - it does not really give value to add that to the screen.

Thanks for the Card - very use full.

**Comment by Barma-lej** [comment]
Fixed in https://github.com/Barma-lej/landroid-card/releases/tag/0.2.5
