### ISSUE TITLE
Border radius is not applied to landroid card

### ISSUE THREAD

**Issue by johannes-z** [Barma-lej/landroid-card#70]
## **Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser. [See here](https://github.com/Barma-lej/landroid-card/issues/3#issuecomment-1176298240)

## **Describe the bug**
I'm using mushroom cards with a `border-radius` of `20px`. `landroid-card` gets a `border-radius` set view the default `:host` rule, but it's not applied because it doesn't specify `overflow: hidden`. However, if you specify `overflow: hidden` the popouts on battery, wifi, etc. are cut off too.

See the screenshots below

## **Steps to reproduce**
`:host` rule `border-radius: var(--ha-card-border-radius, 4px);` doesn't work as `overflow: hidden` is not set - `border-radius` doesn't clip content. Check browser devtools

## **Expected behavior**
`border-radius` should be consistent for all cards.

## **Log, errors**
none

## **Screenshots**
1. ![image](https://user-images.githubusercontent.com/9069888/194756363-f62a6a79-f414-418f-b96d-ad3bfa56a899.png)
2. ![image](https://user-images.githubusercontent.com/9069888/194756380-a25db6d3-0825-4108-be35-28ab3ad8b85b.png)

## **Versions:**
- Release: 0.2.3
- Browser: chrome
- HomeAssistant version: 2022.10.0
- Landroid_cloud integration -

**Comment by Barma-lej** [comment]
i hope that fixed in https://github.com/Barma-lej/landroid-card/releases/tag/0.2.5
