### ISSUE TITLE
How to set up notifications?

### ISSUE THREAD

**Issue by janez33** [Barma-lej/landroid-card#78]
Hello :) I'm quite a newbie here in home assistant community and I have a question if you can help me please :)
I want to know how to set up my card configuration in order to receive mobile push notifications for every status change of the landroid mower or just when it's stucked (error notification)?
Right now my card configuration looks like this:
```
image: default
show_animation: true
compact_view: false
show_name: true
show_status: true
show_configbar: true
show_toolbar: true
type: custom:landroid-card
entity: vacuum.mower
```

**Comment by Barma-lej** [comment]
You have to read this https://companion.home-assistant.io/docs/notifications/notifications-basic/

**Comment by janez33** [comment]
Ok thank you very much 👍👍
