### ISSUE TITLE
set up torque for supported mowers

### ISSUE THREAD

**Issue by mdkeil** [Barma-lej/landroid-card#9]
In your src-code are some commended out code of "set fan speed" from vacuum cleaner. The landroid cloud implementation from MTrab includes the service "landroid_cloud.torque" to set up the torque. Can you pls implement an option to set up this "action"  in further releases?

**Comment by Barma-lej** [comment]
Added in https://github.com/Barma-lej/landroid-card/releases/tag/0.2.5
